// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpsojhykuufuswpbuaju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwc29qaHlrdXVmdXN3cGJ1YWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDQ4MzgsImV4cCI6MjA2NzMyMDgzOH0.KV7zFPF5RX_yEAS-USJmsBUcwhICiulmGcsajnNSJnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});